Updates template for kernel version 5.10.52

diff --git a/srcpkgs/rtl8188eu/template b/srcpkgs/rtl8188eu/template
--- a/srcpkgs/rtl8188eu/template
+++ b/srcpkgs/rtl8188eu/template
@@ -2,9 +2,9 @@
 
 pkgname='rtl8188eu'
 version='5.2.2.4'
-revision='1'
+revision='2'
 arch='armv7l'
-depends=''
+depends='rpi2-kernel>=5.10.52_1'
 
 short_desc='Kernel module for rtl8188eu'
 license='Proprietary'
@@ -20,14 +20,22 @@ prepare() {
 package() {
   unzip -d "${pkgdir}" "${srcdir}/sources.zip"
 
+  # use first kernel version in modules folder
+  cd '/lib/modules'
+  for kernel in *; do break; done
+
+  if [ -z "${kernel}" ]; then
+    echo 'Could not get target kernel version'
+    exit 1
+  fi
+
   cd "${pkgdir}/rtl8188eu-"*
   mkdir .git
 
-  kernel="$(uname -r)"
   make KVER="${kernel}" all
 
-  install -Dm 644 "${pkgdir}/rtl8188eu-"*/8188eu.ko "${pkgdir}/usr/lib/modules/${kernel}/kernel/drivers/net/wireless"
-  install -Dm 644 "${pkgdir}/rtl8188eu-"*/rtl8188eufw.bin "${pkgdir}/usr/lib/firmware/rtlwifi"
+  install -Dm 644 "${pkgdir}/rtl8188eu-"*/8188eu.ko "${pkgdir}/usr/lib/modules/${kernel}/kernel/drivers/net/wireless/8188eu.ko"
+  install -Dm 644 "${pkgdir}/rtl8188eu-"*/rtl8188eufw.bin "${pkgdir}/usr/lib/firmware/rtlwifi/rtl8188eufw.bin"
   install -Dm 644 "${srcdir}/blacklist.conf" "${pkgdir}/etc/modprobe.d/blacklist-r8188eu.conf"
 
   rm -rf "${pkgdir}/rtl8188eu-"*
